### ISSUE TITLE
Why not use Tomcat service

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/vivo_playbook#4]
Is there a reason to use the tomcat command instead of the tomcat service?  
https://github.com/tulibraries/vivo_playbook/blob/master/tasks/vivo.yml#L96-L97

I'd expect something like:

```yaml
- name: Make sure the tomcat service is started
  service:
    name: tomcat
    state: started
    enabled: true
```

alternatively, we could move that into a handler that restarts tomcat if any of the runtime config has been changed, which would be useful if we are going to use this playbook noty just for a one time deploy, but for ongoing maintenance
